import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <header className="border-b border-zinc-200 bg-white shrink-0">
          <nav className="mx-auto max-w-4xl px-4 py-3 flex flex-wrap gap-4 text-sm">
            <Link href="/" className="text-zinc-800 hover:underline">
              Home
            </Link>
            <Link href="/recipes" className="text-zinc-800 hover:underline">
              Recipes
            </Link>
            <Link href="/favorites" className="text-zinc-800 hover:underline">
              Favorites
            </Link>
            <Link href="/categories" className="text-zinc-800 hover:underline">
              Categories
            </Link>
          </nav>
        </header>
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
